baseURL = "https://rumspring.org"
languageCode = "en-us"
title = "Rumspring Crypto-Amish Electric Church Boogaloo"
theme = "mainroad"
[Author] # Used in authorbox
  name = "Brother Jack"
  bio = ""
  avatar = "img/fa.jpg"

[Params]
  description = "Crypto-Amish Electric Church Boogaloo" # Site description. Used in meta description
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  #authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  #mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "January 2, 2006" # Change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  #googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  #customCSS = ["css/custom.css"] # Include custom CSS files
  #customJS = ["js/custom.js"] # Include custom JS files
  CommentoURL = "http://comment.rumspring.org:8080"

[Params.style.vars]
  highlightColor = "#2f004d" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  #fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  #fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  #image = "img/placeholder.png" # Logo image. Path relative to "static"
  title = "Rumspring!" # Logo title, otherwise will use site title
  subtitle = "A Crypto-Amish Church for the Electric Boogaloo" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent","social"] #, "search","categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget


[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://www.youtube.com/channel/UCsgDGg-MwfPIkh0BlYnzLcg"

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  #twitter = "username"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  github = "rumspring"
  email = "yo@rumspring.org"

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/rumspring"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

